version: 0.0.{build}
image: Visual Studio 2017

environment:
  DOCKER_USER:
    secure: zYh2E1Ev8iysKYqh1JQnjA==
  DOCKER_PASS:
    secure: fzKLKWlgyXg+GYPF9tvvrA==

install:
  docker version
build_script:
  - docker build -t solthoth/iis-chocolatey:latest .
  - ps: docker tag solthoth/iis-chocolatey:latest solthoth/iis-chocolatey:"$env:APPVEYOR_BUILD_VERSION"
before_deploy:
  ps: docker login -u "$env:DOCKER_USER" -p "$env:DOCKER_PASS"
deploy_script:
  - docker push solthoth/iis-chocolatey:latest
  - ps: docker push solthoth/iis-chocolatey:"$env:APPVEYOR_BUILD_VERSION"
after_deploy:
  docker logout